### ISSUE TITLE
Rewards for last drone seem broken

### ISSUE THREAD

**Issue by RyanNavillus** [cage-challenge/CybORG#9]
The last agent/drone in the simulation seems to have a very broken reward signal. It quickly converges to -1000 over the course of training. 
Here's an example of the rewards from one training run:
```
First log:
    policy_reward_max:
      blue_agent_0: 0.0
      blue_agent_1: -44.0
    policy_reward_mean:
      blue_agent_0: -12.0
      blue_agent_1: -56.0
    policy_reward_min:
      blue_agent_0: -36.0
      blue_agent_1: -78.0
Second log:
    policy_reward_max:
      blue_agent_0: 0.0
      blue_agent_1: -34.0
    policy_reward_mean:
      blue_agent_0: -13.777777777777779
      blue_agent_1: -125.0
    policy_reward_min:
      blue_agent_0: -36.0
      blue_agent_1: -444.0
Third log: 
  policy_reward_max:
    blue_agent_0: 0.0
    blue_agent_1: -4.0
  policy_reward_mean:
    blue_agent_0: -21.428571428571427
    blue_agent_1: -681.625
  policy_reward_min:
    blue_agent_0: -68.0
    blue_agent_1: -1000.0
```

I tested this with 2 and 3 drones and it seems to always affect the last agent. Any ideas?
